//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題MVC修正.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamMaster
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamMaster()
        {
            this.ExamDetail = new HashSet<ExamDetail>();
            this.StdExamRec = new HashSet<StdExamRec>();
        }
    
        public int ExamID { get; set; }
        public string ExamName { get; set; }
        public System.DateTime ExamSDate { get; set; }
        public System.DateTime ExamEDate { get; set; }
        public double ExamDuraionTime { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamDetail> ExamDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdExamRec> StdExamRec { get; set; }
    }
}
