//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題MVC修正.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExamDetail
    {
        public int ExamDetPK { get; set; }
        public int ExamID { get; set; }
        public string ExamQMode { get; set; }
        public Nullable<int> ExamMQBPK { get; set; }
        public Nullable<int> ExamMQBTeamPK { get; set; }
        public double ExamDefaultScore { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public Nullable<int> ExamQClass { get; set; }
    
        public virtual ExamMaster ExamMaster { get; set; }
        public virtual MoodQuestionBank MoodQuestionBank { get; set; }
        public virtual MQBClassName MQBClassName { get; set; }
        public virtual MQBTeam MQBTeam { get; set; }
    }
}
