//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題MVC修正.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoodQuestionBank
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MoodQuestionBank()
        {
            this.ExamDetail = new HashSet<ExamDetail>();
        }
    
        public int MQBPK { get; set; }
        public int MQBTeamPK { get; set; }
        public int MQBSort { get; set; }
        public int QClass { get; set; }
        public int QType { get; set; }
        public string QContent { get; set; }
        public string QOptionA { get; set; }
        public string QOptionB { get; set; }
        public string QOptionC { get; set; }
        public string QOptionD { get; set; }
        public string QAns { get; set; }
        public byte[] QExplain { get; set; }
        public string ImgQContent { get; set; }
        public string ImgQOptionA { get; set; }
        public string ImgQOptionB { get; set; }
        public string ImgQOptionC { get; set; }
        public string ImgQOptionD { get; set; }
        public string ImgQAns { get; set; }
        public string ImgQExplain { get; set; }
        public Nullable<int> MQBChapter { get; set; }
        public Nullable<int> ChapterDetail { get; set; }
        public Nullable<int> MQBSession { get; set; }
        public byte[] Image { get; set; }
    
        public virtual ChapterDetail ChapterDetail1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamDetail> ExamDetail { get; set; }
        public virtual MQBChapter MQBChapter1 { get; set; }
        public virtual MQBClassName MQBClassName { get; set; }
        public virtual MQBTeam MQBTeam { get; set; }
    }
}
