//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題MVC修正.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MQBEntities : DbContext
    {
        public MQBEntities()
            : base("name=MQBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChapterDetail> ChapterDetail { get; set; }
        public virtual DbSet<ExamDetail> ExamDetail { get; set; }
        public virtual DbSet<ExamMaster> ExamMaster { get; set; }
        public virtual DbSet<MoodQuestionBank> MoodQuestionBank { get; set; }
        public virtual DbSet<MQBChapter> MQBChapter { get; set; }
        public virtual DbSet<MQBClassName> MQBClassName { get; set; }
        public virtual DbSet<MQBSession> MQBSession { get; set; }
        public virtual DbSet<MQBTeam> MQBTeam { get; set; }
        public virtual DbSet<Std> Std { get; set; }
        public virtual DbSet<StdExamRec> StdExamRec { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
