//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題MVC修正.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Std
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Std()
        {
            this.StdExamRec = new HashSet<StdExamRec>();
        }
    
        public int StdPK { get; set; }
        public string StdDepID { get; set; }
        public string StdID { get; set; }
        public string StdName { get; set; }
        public string WorkEmail { get; set; }
        public string PersonalGmail { get; set; }
        public string StdGender { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StdExamRec> StdExamRec { get; set; }
    }
}
