//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 專題MVC修正.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class StdExamRec
    {
        public int StdExamRecPK { get; set; }
        public Nullable<int> ExamID { get; set; }
        public Nullable<int> ExamDetPK { get; set; }
        public Nullable<int> ExamMQBPK { get; set; }
        public Nullable<double> ExamDefaultScore { get; set; }
        public string ExamAns { get; set; }
        public Nullable<int> ExamStdPK { get; set; }
        public string ExamStdAns { get; set; }
        public Nullable<System.DateTime> ExamAnsST { get; set; }
        public Nullable<System.DateTime> ExamAnsET { get; set; }
        public string ExamStdAnsRight { get; set; }
        public string ExamEmotion { get; set; }
        public string ScoreList { get; set; }
        public string PKList { get; set; }
        public string ExamRecStdID { get; set; }
    
        public virtual ExamMaster ExamMaster { get; set; }
        public virtual Std Std { get; set; }
    }
}
